import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import {getMenuData} from "./navMenuApi";


const initialState = {
    pages: ['Home','News','About'], //导航的菜单名称
    settings:['Profile', 'Account', 'Dashboard', 'Logout'] //个人中心导航，profile
};


// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getMenu = createAsyncThunk(
    'navMenuApi/getMenu',
    async () => {
        const response = await getMenuData();
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const navMenuSlice = createSlice({
    name: 'navMenu',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {

    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {

    },
});

export const selectMenu = (state) => state.navMenu.pages;
export const selectSettings = (state) => state.navMenu.settings;
export default navMenuSlice.reducer;

